### ISSUE TITLE
Quotation Marks

### ISSUE THREAD

**Issue by r12a** [w3c/klreq#17]
[raised by Fantasai]

I think there's a Unicode error in

> Full-width opening parentheses and quotation marks positioned in the character frame （｛［〔《「『 ' "  (U+FF08, U+FF5B, U+FF3B, U+3014, U+300A, U+300C, U+300E, U+ 02BB, U+201C) 전각 열기 괄호와 굽은 열기 따옴표의 글자틀 내 위치 （｛［〔《「『 ‘ “ (U+FF08, U+FF5B,  U+FF3B, U+3014, U+300A, U+300C, U+300E, U+ 02BB, U+201C)

U+02BB is MODIFIER LETTER TURNED COMMA
http://www.fileformat.info/info/unicode/char/02bb/index.htm
which is not even a punctuation character.

I am pretty sure this is wrong and it should be U+2018 and U+2019.
http://www.fileformat.info/info/unicode/char/2018/index.htm
http://www.fileformat.info/info/unicode/char/2019/index.htm

**Comment by moyogo** [comment]
Indeed. I had a draft on the same issue.
U+02BB and U+02BC should be replaced by the punctuation characters actually listed. This needs to be corrected in four places.
Also  ' " should be replaced by ‘ “ in two place.

The first:

> cl1. Hangul Opening Parenthesis
> cl1. 한글 열기 괄호
> （｛［〔《「『‘ “ (U+FF08, U+FF5B, U+FF3B, U+3014, U+300A, U+300C, U+300E, U+02BB, U+02BB)
> cl2. Hangul Closing Parenthesis
> cl2. 한글 닫기 괄호
> ）｝］〕》」』’ ” (U+FF09, U+FF5D, U+FF3D, U+3015, U+300B, U+300D, U+300F, U+02BC, U+02BC)

should be:

> cl1. Hangul Opening Parenthesis
> cl1. 한글 열기 괄호
> （｛［〔《「『 ‘ “ (U+FF08, U+FF5B, U+FF3B, U+3014, U+300A, U+300C, U+300E, U+2018, U+201C)
> cl2. Hangul Closing Parenthesis
> cl2. 한글 닫기 괄호
> ）｝］〕》」』’ ” (U+FF09, U+FF5D, U+FF3D, U+3015, U+300B, U+300D, U+300F, U+2019, U+02BC)

The second:

> Fig. 4 Full-width opening parentheses and quotation marks positioned in the character frame >（｛［〔《「『 ' " (U+FF08, U+FF5B, U+FF3B, U+3014, U+300A, U+300C, U+300E, U+ 02BB, >U+201C) 전각 열기 괄호와 굽은 열기 따옴표의 글자틀 내 위치 （｛［〔《「『 ‘ “ (U+FF08, U+FF5B, U+FF3B, U+3014, U+300A, U+300C, U+300E, U+ 02BB, U+201C)

should be:

> Fig. 4 Full-width opening parentheses and quotation marks positioned in the character frame >（｛［〔《「『 ‘ “ (U+FF08, U+FF5B, U+FF3B, U+3014, U+300A, U+300C, U+300E, U+2018, >U+201C) 전각 열기 괄호와 굽은 열기 따옴표의 글자틀 내 위치 （｛［〔《「『 ‘ “ (U+FF08, U+FF5B, U+FF3B, U+3014, U+300A, U+300C, U+300E, U+2018, U+201C)

The third:

> Fig. 5 Full-width closing parentheses and quotation marks positioned in the character frame >）｝］〕》」』' " (U+FF09, U+FF5D, U+FF3D, U+3015, U+300B, U+300D, U+300F, U+02BC, >U+201D) 전각 닫기 괄호와 굽은 닫기 따옴표의 글자틀 내 위치 ）｝］〕》」』’ ” (U+FF09, U+FF5D, U+FF3D, U+3015, U+300B, U+300D, U+300F, U+02BC, U+201D)

should be:

> Fig. 5 Full-width closing parentheses and quotation marks positioned in the character frame >）｝］〕》」』’ ” (U+FF09, U+FF5D, U+FF3D, U+3015, U+300B, U+300D, U+300F, U+02BC, >U+201D) 전각 닫기 괄호와 굽은 닫기 따옴표의 글자틀 내 위치 ）｝］〕》」』’ ” (U+FF09, U+FF5D, U+FF3D, U+3015, U+300B, U+300D, U+300F, U+2019, U+201D)

**Comment by moyogo** [comment]
There’s also another one for ' " to ‘ “

> In horizontal writing; ' [U+2018], ' [U+2019], " [U+201C], " [U+201D]
> 가로짜기의 경우; ‘[U+2018], ’ [U+2019], “[U+201C], ” [U+201D]

should be

> In horizontal writing; ‘ [U+2018], ’ [U+2019], “[U+201C], ” [U+201D]
> 가로짜기의 경우; ‘ [U+2018], ’ [U+2019], “ [U+201C], ” [U+201D]

**Comment by r12a** [comment]
many thanks for spotting this, and moyogo extra thanks for the PR !

now fixed in the ED
